### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by asnganje** [jdbs9514/Recipe-app#19]
## Dear Reviewer

In this project, our team is made up of three partners whose names are listed below

- [AbdulRahman Nganje](https://github.com/asnganje) - Team Member A
- [Josué Benavides](https://github.com/jdbs9514) - Team Member B
- [Kelvin-Ben](https://github.com/Kelvin-Ben)  - Team Member C

Link to our Github Project https://github.com/users/jdbs9514/projects/5

**Comment by Davidosky007** [comment]
Hi @asnganje @Kelvin-Ben @jdbs9514 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong link to your Kanban board project [This should be the right link](https://github.com/users/jdbs9514/projects/5/views/1)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Davidosky007** [comment]
Hi @asnganje @Kelvin-Ben @jdbs9514 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* All team members' info provided 👍 
* Link to project working 👍 

## Required Changes ♻️
* Kindly add descriptions for each task as most of the tasks don't have descriptions 
![image](https://user-images.githubusercontent.com/52497246/217096140-e47ee41a-96a9-4f5b-993d-056b8692b9bb.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alexander16108** [comment]
Hi Team 👋🏾 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kelvin-Ben** [comment]
Thank you for the review @alexander16108 , we will make changes that you have suggested :+1:
